<?php
if($messages) {
    foreach($messages as $message) {
        echo "<div class='alert alert-success'>$message</div>";
    }
}
?>
<h1>Comment Management</h1>

<?php
$form = $this->formSearch;
$form->setAttribute('action',$this->url('comment',array('action'=>'index')));
$form->setAttribute('method','get');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<table class="grid search">
    <tr>
        <th class="span2"><?php echo $this->formLabel($form->get('username')); ?></th>
        <td class="span4"><?php echo $this->formElement($form->get('username')); ?></td>
        <th class="span2"><?php echo $this->formLabel($form->get('sound')); ?></th>
        <td class="span4"><?php echo $this->formElement($form->get('sound')); ?></td>
    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('comment')); ?></th>
        <td><?php echo $this->formElement($form->get('comment')); ?></td>
        <th><?php echo $this->formLabel($form->get('created_at')); ?></th>
        <td><?php echo $this->formElement($form->get('created_at')); ?></td>
    </tr>
    <tr>
        <td class="search-button" colspan="4"><?php echo $this->formElement($form->get('submit')); ?></td>
    </tr>
</table>
<?php echo $this->form()->closeTag(); ?>

<?php if($permissions['add']): ?>
<a class="btn btn-primary add-entity" href="<?php echo $this->url('comment',array('action' => 'add')) ?>">Add</a>
<?php endif; ?>

<table class="table table-striped table-bordered">
    <thead id="thead">
        <tr>
            <th>Id</th>
            <th>Author</th>
            <th>Comment</th>
            <th>In sound</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($comments as $comment): ?>
        <tr>
            <td class="span1"><?php echo $comment->id ?></td>
            <td class="span2">
                <?php echo $comment->display_name.'</br>' ?>
                <a href="<?php echo $this->url('user',array('action' => 'view','id' => $comment->user_id)) ?>"><?php echo $comment->username ?></a>
            </td>
            <td class="span4"><?php echo $comment->comment ?></td>
            <td class="span3"><?php echo $comment->title ?></td>
            <td class="span2">
                <?php if($permissions['edit']): ?>
                <a href="<?php echo $this->url('comment',array('action' => 'edit','id' => $comment->id)) ?>"><i class="icon-pencil"></i>Edit</a>
                <?php endif; ?>
                <?php if($permissions['delete']): ?>
                <a class="delete" href="<?php echo $this->url('comment',array('action' => 'delete','id' => $comment->id)) ?>"><i class="icon-remove"></i>Del</a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php if(!count($comments)): ?>
        <tr><td colspan="5">No data</td></tr>
        <?php endif; ?>
    </tbody>
</table>

<?php 
    echo $this->paginationControl($this->comments,'sliding',array('partial/paginator.phtml', 'Sound'),array('route' => 'comment'));
?>