<?php

$title = 'Change password';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin-user', array('action' => 'change-password')));
$form->setAttribute('class','form-horizontal');
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formRow($form->get('uid')); ?>
<table class="grid">
    <tr>
        <th><?php echo $this->formLabel($form->get('password')); ?></th>
        <td>
            <?php echo $this->formElement($form->get('password')); ?>
            <?php if($this->formElementErrors($form->get('password'))): ?>
            <?php echo $this->formElementErrors($form->get('password')) ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('confirm_password')); ?></th>
        <td>
            <?php echo $this->formElement($form->get('confirm_password')); ?>
            <?php if($this->formElementErrors($form->get('confirm_password'))): ?>
            <?php echo $this->formElementErrors($form->get('confirm_password')) ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <td class="search-button" colspan="2"><?php echo $this->formElement($form->get('submit')); ?></td>
    </tr>
</table>
<?php echo $this->form()->closeTag(); ?>
