<?php
if($messages) {
    foreach($messages as $message) {
        echo "<div class='alert alert-success'>$message</div>";
    }
}
?>
<h1>Admin User Management</h1>
<?php
$form = $this->formSearch;
$form->setAttribute('action',$this->url('admin-user',array('action'=>'index')));
$form->setAttribute('method','get');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>

<table class="grid search">
    <tr>
        <th class="span2"><?php echo $this->formLabel($form->get('username')); ?></th>
        <td class="span4"><?php echo $this->formElement($form->get('username')); ?></td>
        <th class="span2"><?php echo $this->formLabel($form->get('rid')); ?></th>
        <td class="span4"><?php echo $this->formElement($form->get('rid')); ?></td>
    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('status')); ?></th>
        <td><?php echo $this->formElement($form->get('status')); ?></td>
        <th><?php echo $this->formLabel($form->get('created_at')); ?></th>
        <td><?php echo $this->formElement($form->get('created_at')); ?></td>
    </tr>
    <tr>
        <td class="search-button" colspan="4"><?php echo $this->formElement($form->get('submit')); ?></td>
    </tr>
</table>

<?php echo $this->form()->closeTag(); ?>

<?php if($permissions['add']): ?>
<a class="btn btn-primary add-entity" href="<?php echo $this->url('admin-user',array('action' => 'add')) ?>">Add</a>
<?php endif; ?>
<table class="table table-striped table-bordered">
    <thead id="thead">
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Role</th>
            <th>Status</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($users as $user): ?>
        <tr>
            <td class="span1"><?php echo $user->uid ?></td>
            <td class="span4"><?php echo $user->username ?></td>
            <td class="span2"><?php echo ucwords($user->role_name) ?></td>
            <td class="span2"><?php echo ($user->status == 1) ? 'Active' : 'Inactive' ?></td>
            <td class="span3">
                <?php if($permissions['edit']): ?>
                <a href="<?php echo $this->url('admin-user',array('action' => 'edit','uid' => $user->uid)) ?>"><i class="icon-pencil"></i>Edit</a>&nbsp;&nbsp;&nbsp;
                <?php endif; ?>
                <?php if($permissions['delete']): ?>
                <a class="delete" href="<?php echo $this->url('admin-user',array('action' => 'delete','uid' => $user->uid)) ?>"><i class="icon-remove"></i>Del</a>&nbsp;&nbsp;&nbsp;
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php if(!count($users)): ?>
        <tr><td colspan="5">No data</td></tr>
        <?php endif; ?>
    </tbody>
</table>

<?php 
    echo $this->paginationControl($this->users,'sliding',array('partial/paginator.phtml', 'AdminUser'),array('route' => 'admin-user'));
?>