<?php //echo $this->s3Link('oh/sensio-labs_521d9c3a446932.gif','ica467'); ?>
<?php //echo $this->getS3Url('oh/avatar_521d816d633f9.png'); ?>

<h1>User Management</h1>

<?php
$form = $this->formSearch;
$form->setAttribute('action',$this->url('user',array('action'=>'index')));
$form->setAttribute('method','get');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>

<table class="grid search">
    <tr>
        <th class="span2"><?php echo $this->formLabel($form->get('username')); ?></th>
        <td class="span4"><?php echo $this->formElement($form->get('username')); ?></td>
        <th class="span2"><?php echo $this->formLabel($form->get('display_name')); ?></th>
        <td class="span4"><?php echo $this->formElement($form->get('display_name')); ?></td>
    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('full_name')); ?></th>
        <td><?php echo $this->formElement($form->get('full_name')); ?></td>
        <th><?php echo $this->formLabel($form->get('gender')); ?></th>
        <td><?php echo $this->formElement($form->get('gender')); ?></td>
    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('country_id')); ?></th>
        <td><?php echo $this->formElement($form->get('country_id')); ?></td>
        <th><?php echo $this->formLabel($form->get('birthday')); ?></th>
        <td><?php echo $this->formElement($form->get('birthday')); ?></td>
    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('created_at')); ?></th>
        <td><?php echo $this->formElement($form->get('created_at')); ?></td>
        <td class="search-button" colspan="2"><?php echo $this->formElement($form->get('submit')); ?></td>
    </tr>
</table>

<?php echo $this->form()->closeTag(); ?>

<?php if($permissions['add']): ?>
<a class="btn btn-primary add-entity" href="<?php echo $this->url('user',array('action' => 'add')) ?>">Add</a>
<?php endif; ?>

<table class="table table-striped table-bordered">
    <thead id="thead">
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Display Name</th>
            <th>Avatar</th>
            <th>Gender</th>
            <th>Birthday</th>
            <th>Country</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($users as $user): ?>
        <tr>
            <td class="span1"><?php echo $user->id ?></td>
            <td class="span1"><?php echo $user->username ?></td>
            <td class="span2"><?php echo $user->display_name ?></td>
            <td class="span2 text-center">
                <?php if($user->avatar): ?>
                <a class="zoom-image" href="<?php echo $this->getS3Url($user->avatar,'user_avatar_path_upload') ?>">
                <img class="image-listing" src="<?php echo $this->getS3Url($user->avatar,'user_avatar_path_upload') ?>" alt="user avatar" />
                </a>
                <?php endif; ?>
            </td>
            <td class="span1"><?php echo ($user->gender == 1) ? 'Male' : 'Female' ?></td>
            <td class="span2">
                <?php if($user->birthday): ?>
                <?php echo date('Y,M d',strtotime($user->birthday)) ?>
                <?php endif; ?>
            </td>
            <td class="span2"><?php echo $user->country_name ?></td>
            <td class="span2">
                <?php if($permissions['edit']): ?>
                <a href="<?php echo $this->url('user',array('action' => 'edit','id' => $user->id)) ?>"><i class="icon-pencil"></i>Edit</a>
                <?php endif; ?>
                <?php if($permissions['delete']): ?>
                <a class="delete" href="<?php echo $this->url('user',array('action' => 'delete','id' => $user->id)) ?>"><i class="icon-remove"></i>Del</a>
                <?php endif; ?>
                <?php if($permissions['view']): ?>
                <a href="<?php echo $this->url('user',array('action' => 'view','id' => $user->id)) ?>"><i class="icon-eye-open"></i>View</a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php if(!count($users)): ?>
        <tr><td colspan="8">No data</td></tr>
        <?php endif; ?>
    </tbody>
</table>

<?php 
    echo $this->paginationControl($this->users,'sliding',array('partial/paginator.phtml', 'User'),array('route' => 'user'));
?>