<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Permission\Module'                        => __DIR__ . '/Module.php',
    'Permission\Controller\IndexController' => __DIR__ . '/src/Permission/Controller/IndexController.php',
    'PermissionTest\Framework\TestCase'        => __DIR__ . '/tests/Permission/Framework/TestCase.php',
    'PermissionTest\SampleTest'                => __DIR__ . '/tests/Permission/SampleTest.php',
);
