<?php
if($messages) {
    foreach($messages as $message) {
        echo "<div class='alert alert-success'>$message</div>";
    }
}
?>
<h1>Help center</h1>

<?php if($permissions['add']): ?>
<a class="btn btn-primary add-entity" href="<?php echo $this->url('help-center',array('action' => 'add')) ?>">Add</a>
<?php endif; ?>

<table class="table table-striped table-bordered">
    <thead id="thead">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Value</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($helpCenters as $helpCenter): ?>
        <tr>
            <td class="span1"><?php echo $helpCenter->id ?></td>
            <td class="span2"><?php echo $helpCenter->name ?></td>
            <td class="span4"><a href="<?php echo $helpCenter->value ?>" target="_blank"><?php echo $this->wordLimit($helpCenter->value) ?></a></td>
            <td class="span2">
                <?php if($permissions['edit']): ?>
                <a href="<?php echo $this->url('help-center',array('action' => 'edit','id' => $helpCenter->id)) ?>"><i class="icon-pencil"></i>Edit</a>
                <?php endif; ?>
                <?php if($permissions['delete']): ?>
                <a class="delete" href="<?php echo $this->url('help-center',array('action' => 'delete','id' => $helpCenter->id)) ?>"><i class="icon-remove"></i>Del</a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php if(!count($helpCenters)): ?>
        <tr><td colspan="4">No data</td></tr>
        <?php endif; ?>
    </tbody>
</table>