<?php
$title = 'View soundset';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="grid">
    <?php foreach($soundSetItems as $soundSetItem): ?>
    <tr>
        <th style="width: 20%;"><?php echo $soundSetItem->name ?></th>
        <td>
            <?php if($soundSetItem->file): ?>            
            <audio controls>
            <source src="<?php echo $this->getS3Url($soundSetItem->file,'sound_set_item_upload_s3',$soundSetItem->sound_set_id)  ?>" type="audio/mpeg">
            Your browser does not support the audio element.
            </audio>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?> 
    <tr>
        <td colspan="2"><a class="btn" href="<?php echo $this->url('sound-set') ?>">Back</a></td>
    </tr>
</table>