<?php //$auth = new \Zend\Authentication\AuthenticationService();?>
<div class="nav-collapse collapse">
<ul class="nav">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>    
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if( ! $hasChildren): ?>
            <?php if($this->navPrivilege($page->getResource())): ?>
            <li class="<?php echo ($page->isActive() ? 'active' : '') ?>">
            <a class="nav-header" href="<?php echo $page->getHref() ?>">
                <?php echo $this->translate($page->getLabel()) ?>
            </a>
            </li>
            <?php endif; ?>
        <?php else: ?>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#page_<?php echo $count ?>">
                <span><?php echo $this->translate($page->getLabel()) ?></span>
            </a>
            <ul class="dropdown-menu" id="page_<?php echo $count ?>">
            <?php foreach($page->getPages() as $child): ?>
                <?php // when using partials we need to manually check for ACL conditions ?>
                <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                <li>
                    <a href="<?php echo $child->getHref() ?>">
                        <?php echo $this->translate($child->getLabel()) ?>
                    </a>
                </li>
            <?php endforeach ?>
            </ul>
        <?php endif ?>
        <?php $count++ ?>
    <?php endforeach ?>
</ul>
</div>